default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
development:
  <<: *default
  database: path2flight_development
  username: postgres
  password: postgres
test:
  <<: *default
  database: path2flight_development
  username: postgres
  password: postgres